dist: trusty
language: elixir

elixir:
    - 1.3.4
    - 1.4.1
    - 1.5.1
    - 1.6.1

otp_release:
    - 18.3
    - 19.0
    - 20.0

matrix:
  exclude:
    - elixir: 1.3.4
      otp_release: 20.0
    - elixir: 1.4.1
      otp_release: 20.0
    - elixir: 1.6.1
      otp_release: 18.3

script: "mix test"
